config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    root                            to: 'home#index'
    get 'index',                    to: 'home#index'
    get 'sample/index',             to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'

    resources :products,            only: [:show]
    resources :categories,          only: [:show, :index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  scope :includes_prices_and_images, -> { includes(master: [:default_price, :images]) }
  scope :related_products,           -> (product) {
                                       joins(:classifications).
                                         where(spree_products_taxons:
                                           { taxon_id: product.taxon_ids }).
                                         distinct
                                     }
  scope :exclude_product,            -> (product) {
                                       where.not(id: product.id)
                                     }

  scope :sort_descend_by_price,               -> { order("spree_prices.amount DESC") }
  scope :sort_ascend_by_price,                -> { order("spree_prices.amount ASC") }
  scope :sort_newest_by_product_available_on, -> { order("spree_products.available_on DESC") }
  scope :sort_oldest_by_product_available_on, -> { order("spree_products.available_on ASC") }
  scope :order_by,                            -> (order) {
                                                case order
                                                when '高い順' then sort_descend_by_price
                                                when '安い順' then sort_ascend_by_price
                                                when '古い順'
                                                  then sort_oldest_by_product_available_on
                                                else sort_newest_by_product_available_on
                                                end
                                              }
end

app/models/spree/variant_decorator.rb
Spree::Variant.class_eval do
  scope :sort_descend_by_price,               -> { order("spree_prices.amount DESC") }
  scope :sort_ascend_by_price,                -> { order("spree_prices.amount ASC") }
  scope :sort_newest_by_product_available_on, -> { order("spree_products.available_on DESC") }
  scope :sort_oldest_by_product_available_on, -> { order("spree_products.available_on ASC") }
  scope :order_by,                            -> (order) {
                                                case order
                                                when '高い順' then sort_descend_by_price
                                                when '安い順' then sort_ascend_by_price
                                                when '古い順'
                                                  then sort_oldest_by_product_available_on
                                                else sort_newest_by_product_available_on
                                                end
                                              }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  before_action :common

  def common
    @taxonomies = Spree::Taxonomy.all.includes(:root)
    @color_list = Spree::OptionType.find_by(name: 'tshirt-color').option_values
    @size_list = Spree::OptionType.find_by(name: "tshirt-size").option_values
    @display = params[:display] == "list" ? "list" : "grid"
  end

  def show
    @taxon = Spree::Taxon.find(params[:id])
    # @taxonomies = Spree::Taxonomy.all.includes(:root)
    @products = Spree::Product.in_taxon(@taxon).
      includes_prices_and_images.
      reorder(nil).
      order_by(params[:order])
    # @display = params[:type] == "list" ? "list" : "grid"
  end

  def index
    @option_value = Spree::OptionValue.find_by(name: params[:option_name])
    if params[:option_name].present?
      @products = @option_value.variants.
        includes([:product, :default_price]).
        reorder(nil).
        order_by(params[:order])
    else
      @products = Spree::Product.all
    end
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  THE_NUMBER_OF_PRODUCTS = 9
  def index
    @new_products = Spree::Product.
      includes_prices_and_images.
      order(available_on: :desc).
      limit(THE_NUMBER_OF_PRODUCTS)
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  THE_NUMBER_OF_RELATED_PRODUCTS = 4
  def show
    @product = Spree::Variant.find(params[:id])
    @product_properties = @product.product.product_properties.includes(:property)
    @related_products = Spree::Product.includes_prices_and_images.
      related_products(@product.product).
      exclude_product(@product.product).
      limit(THE_NUMBER_OF_RELATED_PRODUCTS)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'BIGBAG Store'
    if page_title.empty?
      base_title
    else
      page_title + ' - ' + base_title
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= render 'shared/head'%>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="main-wrapper">
      <%= render 'shared/header'%>
      <%= render 'shared/light_top'%>
      <%= yield %>
      <%= render 'shared/footer'%>
    </div>
    <%= render 'shared/modal'%>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/categories/_filter_color.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">色から探す</div>
  <div class="panel-body">
    <ul class="list-unstyled">
      <% color_list.each do |color| %>
        <li>
          <%= link_to potepan_categories_path(option_name: "#{color.name}") do %>
          <%= color.name %><span><%= "(#{color.variants.count})" %></span>
          <% end %>
        </li>
      <% end %>
      <!-- <li><a href="#">ブラック<span>(15)</span></a></li>
      <li><a href="#">ホワイト<span>(10)</span></a></li>
      <li><a href="#">レッド<span>(7)</span></a></li>
      <li><a href="#">ブルー<span>(12)</span></a></li>
      <li><a href="#">オレンジ<span>(12)</span></a></li> -->
    </ul>
  </div>
</div>

app/views/potepan/categories/_filter_price.html.erb
<div class="panel panel-default priceRange">
  <div class="panel-heading">Price</div>
  <div class="panel-body clearfix">
    <div class="price-slider-inner">
      <span class="amount-wrapper">
        <input type="text" id="price-amount-1" readonly>
        <strong>-</strong>
        <input type="text" id="price-amount-2" readonly>
      </span>
      <div id="price-range"></div>
    </div>
    <input class="btn btn-default" type="submit" value="絞り込む">
  </div>
</div>

app/views/potepan/categories/_filter_size.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">サイズから探す</div>
  <div class="panel-body">
    <ul class="list-unstyled clearfix">
      <% size_list.each do |size| %>
        <li>
          <%= link_to potepan_categories_path(option_name: "#{size.name}") do %>
          <%= size.name %><span><%= "(#{size.variants.count})" %></span>
          <% end %>
        </li>
      <% end %>
      <!-- <li><a href="#">S<span>(15)</span></a></li>
      <li><a href="#">M<span>(10)</span></a></li>
      <li><a href="#">L<span>(7)</span></a></li>
      <li><a href="#">XL<span>(12)</span></a></li> -->
    </ul>
  </div>
</div>

app/views/potepan/categories/_filter_taxon.html.erb
<div class="panel panel-default">
  <div class="panel-heading">CATEGORIES &amp; BRANDS</div>
  <div class="panel-body">
    <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
      <ul class="nav navbar-nav side-nav">
        <% taxonomies.each do |taxonomy| %>
        <li>
          <a href="javascript:;" data-toggle="collapse" data-target="#<%= taxonomy.id %>">
            <%= taxonomy.name %><i class="fa fa-plus"></i>
          </a>
          <ul id="<%= taxonomy.id %>" class="collapse collapseItem">
            <li>
              <%= link_to potepan_category_path(taxonomy.root.id) do %>
                <i class="fa fa-caret-right" aria-hidden="true"></i>
                ALL <span>(<%= Spree::Product.in_taxon(taxonomy.root).count %>)</span>
              <% end %>
            </li>
            <% taxonomy.root.leaves.each do |taxon| %>
              <li>
                <%= link_to potepan_category_path(taxon.id) do %>
                  <i class="fa fa-caret-right" aria-hidden="true"></i>
                  <%= taxon.name %> <span>(<%= taxon.products.count %>)</span>
                <% end %>
              </li>
            <% end %>
          </ul>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/categories/_grid.html.erb
<div class="col-sm-4 col-xs-12">
  <div class="productBox">
    <div class="productImage clearfix">
      <%= image_tag(product.display_image.attachment) %>
      <div class="productMasking">
        <ul class="list-inline btn-group" role="group">
          <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
          <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
          <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
        </ul>
      </div>
    </div>
    <%= link_to potepan_product_path(product.id), class: "productCaption clearfix" do %>
      <h5><%= product.name %></h5>
      <h3><%= product.display_price %></h3>
    <% end %>
  </div>
</div>

app/views/potepan/categories/_light_bottom.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-04.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-05.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/categories/_list.html.erb
<div class="row productListSingle">
  <div class="col-xs-12">
    <div class="media">
      <div class="media-left">
        <%= image_tag(product.display_image.attachment) %>
        <span class="maskingImage"><a data-toggle="modal" href=".quick-view" class="btn viewBtn">Quick View</a></span>
      </div>
      <div class="media-body">
        <%= link_to potepan_product_path(product.id), class: "media-heading" do %>
          <h4><%= product.name %></h4>
          <p><%= product.description %></p>
        <% end %>
        <h3><%= product.display_price %></h3>
        <div class="btn-group" role="group">
          <button type="button" class="btn btn-default" data-toggle="modal" data-target=".login-modal"><i class="fa fa-heart" aria-hidden="true"></i></button>
          <button type="button" class="btn btn-default" onclick="location.href='cart-page.html';"><i class="fa fa-shopping-cart" aria-hidden="true"></i></button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/potepan/categories/_products_menubar.html.erb
<div class="row filterArea">
  <div class="col-xs-6">
    <select name="guiest_id1" id="guiest_id1" class="select-drop">
      <option value="0">並び替え</option>
      <option value="1">人気順</option>
      <option value="2">安い順</option>
      <option value="3">新着順</option>
      <option value="3">高い順</option>
    </select>
  </div>
  <div class="col-xs-6">
    <div class="btn-group pull-right" role="group">
      <%= link_to potepan_category_url(@taxon.id, type: "grid") do %>
        <button type="button" class="<%= @display == "grid" ? "btn btn-default active" : "btn btn-default" %>">
        <i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
      <% end %>
      <%= link_to potepan_category_url(@taxon.id, type: "list") do %>
        <button type="button" class="<%= @display == "list" ? "btn btn-default active" : "btn btn-default" %>">
        <i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
      <% end %>
    </div>
  </div>
</div>

app/views/potepan/categories/_sidebar.html.erb
<%= render partial: 'filter_taxon', locals: {taxonomies: @taxonomies}%>
<%= render partial: 'filter_price'%>
<%= render partial: 'filter_color', locals: { color_list: @color_list} %>
<%= render partial: 'filter_size', locals:  {size_list: @size_list }%>

app/views/potepan/categories/index.html.erb
<% provide(:title, @option_value.name) %>
<%= render 'shared/categories_show' %>

app/views/potepan/categories/show.html.erb
<% provide(:title, @taxon.name) %>
<%= render 'shared/categories_show' %>

app/views/potepan/home/_light_bottom.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-04.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-05.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/home/_new_products.html.erb
<div class="slide">
  <div class="productImage clearfix">
    <%= image_tag(new_product.display_image.attachment.url(:product), :alt => "featured-product-img") %>
    <div class="productMasking">
      <ul class="list-inline btn-group" role="group">
        <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
        <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
        <li><a data-toggle="modal" href=".quick-view" class="btn btn-default"><i class="fa fa-eye"></i></a></li>
      </ul>
    </div>
  </div>
  <div class="productCaption clearfix">
    <%= link_to potepan_product_path(new_product.id) do %>
      <h5><%= new_product.name %></h5>
      <h3><%= new_product.display_price %></h3>
    <% end %>
  </div>
</div>

app/views/potepan/products/_product_properties.html.erb
<li><%= "#{product_property.property.presentation} -------- #{product_property.value}" %></li>

app/views/potepan/products/_related_products.html.erb
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="productBox">
    <div class="productImage clearfix">
      <%= image_tag(related_product.display_image.attachment.url(:product), :alt => "products-img") %>
      <div class="productMasking">
        <ul class="list-inline btn-group" role="group">
          <li>
            <a data-toggle="modal" href=".login-modal" class="btn btn-default">
              <i class="fa fa-heart"></i>
            </a>
          </li>
          <li>
            <a href="cart_page.html" class="btn btn-default">
              <i class="fa fa-shopping-cart"></i>
            </a>
          </li>
          <li>
            <a class="btn btn-default" data-toggle="modal" href=".quick-view">
              <i class="fa fa-eye"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <div class="productCaption clearfix">
      <%= link_to potepan_product_path(related_product.id) do %>
        <h5><%= related_product.name %></h5>
        <h3><%= related_product.display_price %></h3>
      <% end %>
    </div>
  </div>
</div>

app/views/potepan/products/_specified_product.html.erb
<div class="row singleProduct">
  <div class="col-xs-12">
    <div class="media">
      <div class="media-left productSlider">
        <div id="carousel" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <% images.each_with_index do |image, i|  %>
              <div class="item <%= "active" if i == 0 %>" data-thumb="<%= i %>">
                <%= image_tag(image.attachment.url(:large)) %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="clearfix">
          <div id="thumbcarousel" class="carousel slide" data-interval="false">
            <div class="carousel-inner">
              <% images.each_with_index do |image, i| %>
                <div data-target="#carousel" data-slide-to="<%= i %>" class="thumb">
                  <%= image_tag(image.attachment.url(:small)) %>
                </div>
              <% end %>
            </div>
            <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
          </div>
        </div>
      </div>
      <div class="media-body">
        <ul class="list-inline">
          <li><i class="fa fa-reply" aria-hidden="true"></i><%= link_to "一覧ページへ戻る", potepan_category_path(Spree::Taxon.root.id) %></li>
        </ul>
        <h2><%= @product.name %></h2>
        <h3><%= @product.display_price %></h3>
        <p><%= @product.description %></p>
        <span class="quick-drop">
          <select name="guiest_id3" id="guiest_id3" class="select-drop">
            <option value="0">S</option>
            <option value="1">M</option>
            <option value="2">L</option>
            <option value="3">XL</option>
          </select>
        </span>
        <span class="quick-drop resizeWidth">
          <select name="guiest_id4" id="guiest_id4" class="select-drop">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
          </select>
        </span>
        <div class="btn-area">
          <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i></a>
        </div>
        <div class="tabArea">
          <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#details">details</a></li>
            <li><a data-toggle="tab" href="#about-art">about art</a></li>
            <li><a data-toggle="tab" href="#sizing">sizing</a></li>
            <li><a data-toggle="tab" href="#shipping">shipping</a></li>
          </ul>
          <div class="tab-content">
            <div id="details" class="tab-pane fade in active">
              <ul class="list-unstyled">
                <%= render partial: "product_properties", collection: @product_properties, as: 'product_property'%>
              </ul>
            </div>
            <div id="about-art" class="tab-pane fade">
              <p>Nulla facilisi. Mauris efficitur, massa et iaculis accumsan, mauris velit ultrices purus, quis condimentum nibh dolor ut tortor. Donec egestas tortor quis mattis gravida. Ut efficitur elit vitae dignissim volutpat. </p>
            </div>
            <div id="sizing" class="tab-pane fade">
              <p>Praesent dui felis, gravida a auctor at, facilisis commodo ipsum. Cras eu faucibus justo. Nullam varius cursus nisi, sed elementum sem sagittis at. Nulla tellus massa, vestibulum a commodo facilisis, pulvinar convallis nunc.</p>
            </div>
            <div id="shipping" class="tab-pane fade">
              <p>Mauris lobortis augue ex, ut faucibus nisi mollis ac. Sed volutpat scelerisque ex ut ullamcorper. Cras at velit quis sapien dapibus laoreet a id odio. Sed sit amet accumsan ante, eu congue metus. Aenean eros tortor, cursus quis feugiat sed, vestibulum vel purus.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_categories_menubar.html.erb
<%= link_to potepan_category_url(id: @taxon.id, display: "grid", option_name: params[:option_name]) do %>
<button type="button" class="<%= @display == "grid" ? "btn btn-default active" : "btn btn-default" %>">
  <i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
<% end %>
<%= link_to potepan_category_url(id: @taxon.id, display: "list", option_name: params[:option_name]) do %>
<button type="button" class="<%= @display == "list" ? "btn btn-default active" : "btn btn-default" %>">
  <i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
<% end %>

app/views/shared/_grid.html.erb
<div class="col-sm-4 col-xs-12">
  <div class="productBox">
    <div class="productImage clearfix">
      <%= image_tag(product.display_image.attachment) %>
      <div class="productMasking">
        <ul class="list-inline btn-group" role="group">
          <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
          <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
          <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
        </ul>
      </div>
    </div>
    <%= link_to potepan_product_path(product.id), class: "productCaption clearfix" do %>
      <h5><%= product.name %></h5>
      <h3><%= product.display_price %></h3>
    <% end %>
  </div>
</div>

app/views/shared/_light_top.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= yield(:title) %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to("Home", potepan_index_path) %>
          </li>
          <li>
            <%= link_to("Shop", potepan_category_path(Spree::Taxon.root.id)) %>
          </li>
          <li class="active"><%= yield(:title) %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/shared/_list.html.erb
<div class="row productListSingle">
  <div class="col-xs-12">
    <div class="media">
      <div class="media-left">
        <%= image_tag(product.display_image.attachment) %>
        <span class="maskingImage"><a data-toggle="modal" href=".quick-view" class="btn viewBtn">Quick View</a></span>
      </div>
      <div class="media-body">
        <%= link_to potepan_product_path(product.id), class: "media-heading" do %>
          <h4><%= product.name %></h4>
        <% end %>
        <p><%= product.description %></p>
        <h3><%= product.display_price %></h3>
        <div class="btn-group" role="group">
          <button type="button" class="btn btn-default" data-toggle="modal" data-target=".login-modal"><i class="fa fa-heart" aria-hidden="true"></i></button>
          <button type="button" class="btn btn-default" onclick="location.href='cart-page.html';"><i class="fa fa-shopping-cart" aria-hidden="true"></i></button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_products_menubar.html.erb
<%= link_to potepan_categories_url(display: "grid", option_name: params[:option_name]) do %>
<button type="button" class="<%= @display == "grid" ? "btn btn-default active" : "btn btn-default" %>">
  <i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
<% end %>
<%= link_to potepan_categories_url(display: "list", option_name: params[:option_name]) do %>
<button type="button" class="<%= @display == "list" ? "btn btn-default active" : "btn btn-default" %>">
  <i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
<% end %>

app/views/shared/_select_menubar.html.erb
<div class="row filterArea">
  <div class="col-xs-6">
    <%if params[:option_name]%>
      <%= form_tag(potepan_categories_path(params[:id]), method: :get) do %>
        <%= select_tag 'order', options_for_select(['並び替え','新着順',
          '安い順','高い順', '古い順'],
           selected: params[:order] || '新着順'), { class: "select-drop", onChange: "this.form.submit()" } %>
           <%= hidden_field_tag :option_name, params[:option_name] %>
           <%= hidden_field_tag :display, @display %>
      <% end %>
    <%else%>
      <%= form_tag(potepan_category_path(params[:id]), method: :get) do %>
        <%= select_tag 'order', options_for_select(['並び替え','新着順',
          '安い順','高い順', '古い順'],
           selected: params[:order] || '新着順'), { class: "select-drop", onChange: "this.form.submit()" } %>
           <%= hidden_field_tag :display, @display %>
      <% end %>
    <%end%>
  </div>
  <div class="col-xs-6">
    <div class="btn-group pull-right" role="group">
      <% if @taxon %>
        <%= render 'shared/categories_menubar' %>
      <% else %>
        <%= render 'shared/products_menubar'%>
      <% end %>
    </div>
  </div>
</div>